### ISSUE TITLE
SyntaxError: 'return' outside of function

### ISSUE THREAD

**Issue by zaweb** [lordnull/dice.js#21] opened 2017-03-14 21:27 UTC
This dice roller is exactly what I'm looking for. Unfortunately, it doesn't seem to work properly (or at least I can't get it to work). 

I installed dice.js via npm (0.9.2) and am trying to use it in my ReactJS app. So I include it at the stop of my file: 
`var dice = require('dice.js')`

Unfortunately, it produces this error:

Failed to compile.

Error in ./~/dice.js/src/dice.js
Module parse failed: /SomePath/MyRiftsGenerator/node_modules/dice.js/src/dice.js 'return' outside of function (163:0)
You may need an appropriate loader to handle this file type.
SyntaxError: 'return' outside of function (163:0)

I'm at a loss on how to work around this.

Thanks!

**Comment by Morgul** [comment] 2017-03-14 23:28
The problem here is that `package.json` points to `src/dice.js`. However, `src/dice.js` is not _technically_ a valid CommonJS module. (It is, _technically_ a valid node module.)

I pulled down the published package, and it appears that the code in the repo is out of date with what's been published on npm. However the crux of the issue is that the module has a return statement, which is not valid in some loaders, but technically works fine on the cli in node itself.

What you should do, for now, is this:

```javascript
const dice = require('dice.js/build/dice.js');
```

That points you to the version compiled for browsers, which is wrapped up in a UMD, allowing it to be loaded as a CommonJS module by whatever loader you're using. (Does ReactJS have it's own `require` implementation, or are you use Webpack/Browserify?)

@lordnull We should probably get the latest code into master, and then look at making whatever `package.json` points to a more standard CommonJS module, and kill that return statement. (I'm guessing there's some PegJS weirdness here to complicate things.)

**Comment by zaweb** [comment] 2017-03-15 21:31
Thank you for the speedy response!

Doing what you suggested gets rid of the error, but I can't seem to get it
to do anything. For example:
const dice = require('dice.js/build/dice.js');
console.log("dice: ", dice.roll("1D10"))

The output is blank. I could be executing this incorrectly, but I just
wanted to double-check.

Regarding your question, I'm using "create-react-app", which is a layer on
top of webpack and Babel. More info here
<https://github.com/facebookincubator/create-react-app>.

Thanks again!

**Comment by lordnull** [comment] 2017-03-15 21:48
The core problem should be addressed in #22 , so if either of you would like to take a look and give it a sanity check, that would be greatly appreciated.

As for the problem you've having, the roll type indicator (the `d` in `1d20` or `w` in `3w6`) is case sensitive. If `D` or `W` is used, then a `SyntaxError` exception is generated.

I primarily test this using `make dbgtest`, which launches chrome and runs the same tests as on node.  Doing a raw inclusion in a script tag also generates expected behavior. In short, I'm not sure why there would be no output.

Before I go and consider making the roll type indicator case in-sensitve, I'd like to make sure it works as is.

**Comment by zaweb** [comment] 2017-03-15 22:07
Go figure I'm writing an app for the one gaming system that uses a capital
"D" instead of the lowercase "d". :-)  No big deal, I'm glad that's all it
was.

Thanks for the help, it works great now!

**Comment by lordnull** [comment] 2017-03-15 22:56
I've pushed the new version with the fix up to npm, so 9.3 should be in sync w/ the tag on GitHub. Thanks for bringing this to my attention :).

**Closed as completed by lordnull** 2017-03-15 22:56 UTC
Labels: bug
